### ISSUE TITLE
Add --compare flag

### ISSUE THREAD

**Issue by chrisdone** [vincenthz/hs-gauge#68]
When generating results, it would be nice to provide a `--save baseline` flag that would produce e.g.

```
bench1    ██████░░░░░░   41.65 ns
bench2    ████████████   163.9 ns
bench3    ██░░░░░░░░░░   21.25 ns

Saved to: baseline
````

And write the benchmark results to a file in the current directory e.g. `.gauge/saves/`.

And then you could re-run (like when you run a test suite again with `--seed`) with 

    --compare baseline --save inline

and you would get:

```
bench1
  baseline:     ██████░░░░░░   41.65 ns
  inline:       ████░░░░░░░░   32.65 ns
bench2
  baseline:     ████████████   163.9 ns
  inline:       █████████░░░   113.9 ns
bench3
  baseline:     ██░░░░░░░░░░   21.25 ns
  inline:       ██░░░░░░░░░░   20.22 ns

Saved to: inline
````

This would be a great way to optimize things and experiment with ideas. Other tooling could also use it, e.g. Emacs could automate this. The `--compare` could be passed many times to compare many benchmark results at once.

**Comment by vincenthz** [comment]
This is one of my reason to have gauge in the first place, so going in this direction is definitely something I've planned to do eventually. Couple of brain dump points:

* we need to be able to compare different runs consistently; the code is structured in a way that different iterations could give different results, because the initial calibration could give different baseline I think.
* need to workout what need to be save. I would guess CSV raw measurement (`--csvraw`) is the way to go here.
