### ISSUE TITLE
Report estimated time rather than mean in short output?

### ISSUE THREAD

**Issue by istathar** [vincenthz/hs-gauge#86]
Given the amount of effort the original library went to computing kernel density estimates et al wouldn't the _time_ field be better to put into the `--short` version of the output rather than _mean_?

AfC

**Comment by harendra-kumar** [comment]
In fact, I want to get rid of "time" field from the long output as well or at least report "mean" before we report it. In my experience I have found the "time" field to be misleading at times and way off the real. I have found "mean" to be more reliable. Because of frequent problems that I faced because of this, I have now hardcoded `--small` (should be `--short`) in the benchmarking  command that I use. I think this happens especially when the number of samples are fewer, which is the case when we use the quick mode. When the number of samples are more, anyway "mean" and "time" are pretty close, so why use "time" when "mean" is reliable in more cases?

That said, we could report "time" when the user specifically requests a statistical analysis, in that case the user is aware of what to expect, and we can warn when the number of samples is not enough. But in the default mode I think it is not very useful, in fact it could be harmful at times.

**Comment by istathar** [comment]
> "real"
> "more reliable"

Uh, you're saying you want the straight up mean rather than the regression analysis? Huh.

In my brief experience with Haskell benchmarking, knowing that there were outliers was a significant warning sign that there was overmuch allocation going on. That was a cue to go and do some profiling, hunt that down, and then return to benchmarking (usually showing significant improvement) — at least, that was what we did whenever we saw a big bump of time happening in the KDE plot off to the right.

My _impression_ reading http://www.serpentine.com/criterion/tutorial.html#understanding-the-data-under-a-chart is that the ordinary least squares method should give a better estimate on the assumption that the error is normally distributed, which seems likely given the way the benchmarking [calculation] is formulated. You're the ones who have inherited this codebase, though, so you'd know better now I'm sure.

> we could report "time" when the user specifically requests a statistical analysis

(as a user) when would I ever _not_ want that?

AfC

**Comment by harendra-kumar** [comment]
Well, I have never tried to understand the statistical analysis because I never felt the need. And, I would not trust it unless I understand it. My practical observations make me not trust it for now. I have seen the "time" values to be outside the range of measured values, my non-statistical intuition says WTF, though I may be wrong. That's why I say mean is more reliable. See #69 for an example. 

The problem with "time" seems to be related to insufficient samples and perhaps can be fixed by refusing to do analysis when the number of samples are not enough. Or whenever we find that the "time" value is outside the actual ranges. I guess, I will be okay with this kind of arrangement and reporting "time" instead of "mean". However, even then I don't see "time" to be significantly better than mean.

I think one reason why I never cared about the statistical analysis is because I always benchmark a computation that takes a significant amount of time. I distrust the benchmarking application doing it right for me. Rather than benchmarking a single iteration that takes a few nanoseconds for example, my benchmarks are like a loop with million iterations. That I believe removes statistical aberrations. 

Irrespective of that let's analyze what can actually cause the aberrations. I can think of two cases, internal causes and external causes. Internal cause could be a GC kicking in sometimes and other times not. These can be removed by performing a GC before the experiment and by performing the computation for a significant amount of time. Nevertheless, GC can still be unpredictable, but I guess a mean is good enough to smoothen it, in my observation it is in fact very close to "time" when time is reported correctly. 

The external factors could be load on the machine affecting CPU frequency or increasing context switches or memory latencies. I usually do not run anything else on the machine when running a benchmark, and I have observed the results to be quite stable with that.

> (as a user) when would I ever not want that?

During a dev cycle you want quick results. The bulk of the benchmarking would be done in the dev cycle and it should be quick otherwise nobody will actually do it as often. Try the `--quick` option of gauge to see what I am saying. For statistical analysis to work well you need enough samples and therefore have to spend much more time waiting for the benchmark results, and the results are only slightly better, the difference has never been practically useful to me. You can afford to spend more time for less frequent benchmarking e.g. when you are close to a release.

My conclusion is that statistical analysis is a big hammer and is not worth the pains. If we can prove that it is really helpful in one particular case I will be happy to concede and use it.

**Comment by harendra-kumar** [comment]
See also #75 .

**Comment by harendra-kumar** [comment]
I believe we should focus on trying to make benchmarking more reliable and remove the cause of outliers in the first place, if possible, rather than using statistical analysis to weed them out or to somehow arrive at a single value from a bunch of unreliable values. It should be a last resort, only if we know that it is not possible or very hard to do so.

**Comment by istathar** [comment]
@harendra-kumar so clearly I'm not going to convince you that the statistical analysis is important, but I'll leave you with three thoughts:

1. I work in an office with several dozen data scientists who have (to say the least) reinforced the  necessity of rigourous statistics.
2. The whole point of **criterion** and the **statistics** libraries that @bos wrote was to carry out that sort of analysis
3. You might be interested in a recent fascinating article on the [challenges of benchmarking language runtimes](https://tratt.net/laurie/blog/entries/why_arent_more_users_more_happy_with_our_vms_part_1.html). For my part, the extreme lengths that **criterion** went (and, as far as I can tell, **gauge** still goes) to calibrate the clock and then do sufficient samples to bootstrap a simple regression analysis and subsequently gather the data together in a KDE (something which the text-only output doesn't quite capture) was nothing short of miraculous, certainly given the state of out-of-the-box tools in almost any other language.

I'm not sure you want to give up those advantages.  *I* don't pretend to know what I'm doing, but I rely on good tools that do. As I said, I'm surrounded by PhDs in statistics, and a few of them know Haskell. If you'd like someone to have a chat with you about the topic I can certainly ask them to drop by a convenient channel.

Best of luck with your project.

AfC

**Comment by harendra-kumar** [comment]
I do not deny that statistical analysis is useful in general, that would be presumptuous, machine learning, a hugely popular and successful technique is statistics after all. The only question is when, where and how to use this tool, what exactly are we studying, what are the factors causing variance and what insight do we gain by measuring it. If we have a reason to believe that there are genuine cases of significant variance, then definitely we should do it, it will reveal how those factors are playing, giving us an insight into how they are affecting us. That's why I tried to list those reasons in my previous comment. 

My claim is that I do not gain much insight by performing a rigorous statistical analysis of the microbenchmark results of Haskell programs that can help me pinpoint a problem which I can then go and fix. All the sophistication or complexity is of no use to me unless I can do something with it. Maybe it does help, I am searching for an example where it does. I know of cases where it actually caused harm because it had bugs due to the complexity and therefore reported wrong results. I fixed several cases of incorrect measurements/reporting in gauge (inherited from criterion). 

Where do I benefit from it? One case where I see it can possibly help is if we are benchmarking something that is affected by random or dynamic events, e.g. a large/complex program deployed in production. In microbenchmarks I do not see it to be much useful.

The article that you pointed to talks about JIT which is a big dynamic factor and can be a big cause of variance in deployed systems based on which path is taken at runtime. A statistical analysis can definitely give insight into it. But again if we microbenchmark something on a VM, JIT would probably be a one time factor.

**Comment by istathar** [comment]
>  fixed several cases of incorrect measurements/reporting in gauge (inherited from criterion).

That's excellent. You and @vincenthz having picked up this vital piece of the Haskell ecosystem is really appreciated.

As for the relevance (and preference for) "statistical analysis" vs "program time ÷ number of runs", perhaps we can ask around for some help maintaining the bootstrapping, sampling, and regression code part of the codebase if it's not your thing.

**Comment by vincenthz** [comment]
@afcowie: I think you’re convinced that you need this statistical analysis more than knowing you need it.

As @harendra-kumar said, try with —quick and without and compare the number you get. It’s very likely going to be near (which you can repeat many time) that it’s not really worth it to wait for those bench. Now most of the time I only reserve the stastical approach at the end and use quick to get very fast turnaround feedback loop on my benchmarks

**Comment by harendra-kumar** [comment]
@afcowie I toyed around a bit with using statistical analysis in the bench-graph package. Found a couple of bugs in the statistics package as well during this process (e.g. bootstrapBCA crashed with index out of bounds). Looks like that library is heavily used but I found bugs in the first use (that happens to me quite often).

So here is the first part of the story, I did not find any practical difference in the plain average time and the mean computed by bootstrap analysis with 1000 resamples. I ran the same benchmarks three times, computed the difference from the first. The % variance reported across runs when using bootstrap analysis seemed more compared to the one when using plain average. It takes a lot of time building it, a lot of CPU running it, it is potentially a source of bugs because of the complexity/dependencies involved, and in the end we seem to be a bit worse than plain averaging. I seriously wanted to use it but I can't see the benefit. 

Some of the results with plain average:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base) default(3)(%)(-base)
--------------------------------------- -------------------- -------------------- -------------------- --------------------
serially/compose/all-in-filters                     97489.29                -0.54                +0.16                +1.74
serially/compose/all-out-filters                    65179.50                -0.95                -1.28                +0.47
serially/compose/map-with-all-in-filter             95855.57                +1.64                +1.48                +2.51
serially/compose/mapM                               63538.44                +2.21                +2.78                +4.14
serially/elimination/all                            48368.84                -0.53                +0.84                +2.37
serially/elimination/and                            48955.19                -1.20                -0.61                +0.07
serially/elimination/any                            48751.80                -0.12                +0.80                +0.65
serially/elimination/elem                           48181.47                +0.23                -0.27                +2.99
serially/elimination/elemIndex                    2605468.60                -0.67                +0.15                +3.07
serially/elimination/find                          612956.31                +0.55                +0.96                +3.61
serially/elimination/findIndex                    2595750.00                +0.68                +3.24                +1.40
serially/elimination/foldl'                         64484.39                +0.74                +2.02                +0.42
serially/elimination/foldl1'                     15331375.35               -10.35                -8.92                -9.53
serially/elimination/foldr                        4568515.01                +0.01                -0.18                +2.67
serially/elimination/foldr1                      13409848.60                -1.25                +1.06                +0.13
serially/elimination/foldrM                       4514384.79                +2.54                +1.99                +0.96
serially/elimination/init                         3026732.77                -0.09                +0.15                +6.40
serially/elimination/last                           64553.22                -0.28                +1.25                +1.62
serially/elimination/length                         64729.57                +0.18                -1.71                +0.95
serially/elimination/mapM_                          65140.80                -0.86                -0.30                +0.79
serially/elimination/maximum                        64482.93                +0.22                +0.84                +1.00
serially/elimination/minimum                        64941.69                -0.09                +0.29                +0.36
serially/elimination/notElem                        48440.92                -0.13                +0.60                +2.99
serially/elimination/nullHeadTail                 2252744.47                +1.16                +2.48                +7.14
serially/elimination/or                             49021.55                +0.18                +2.04                +2.05
serially/elimination/product                        96604.35                -0.22                +0.66                +1.52
serially/elimination/sum                            64605.94                +0.48                +1.54                +3.05
serially/elimination/tail                          791119.54                -0.57                -0.19                +3.69
serially/elimination/toList                       4598124.88                -0.15                +1.84                -0.32
serially/elimination/toNull                         65170.81                -0.36                -1.31                +1.02
```

Same results using bootstrap with 100 resamples:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base) default(3)(%)(-base)
--------------------------------------- -------------------- -------------------- -------------------- --------------------
serially/compose/all-in-filters                     98012.27                -0.91                -0.80                +1.76
serially/compose/all-out-filters                    65090.19                -0.21                -0.45                +0.46
serially/compose/map-with-all-in-filter             95018.78                +2.50                +2.56                +3.99
serially/compose/mapM                               63288.75                +2.43                +3.93                +4.42
serially/elimination/all                            48500.48                -1.04                +1.45                +2.45
serially/elimination/and                            49253.72                -1.50                -1.29                -0.10
serially/elimination/any                            49023.88                -0.77                +1.21                -0.43
serially/elimination/elem                           47977.61                +0.73                -0.12                +4.20
serially/elimination/elemIndex                    2591684.66                -0.12                +0.01                +4.61
serially/elimination/find                          611325.24                +0.83                +0.52                +4.09
serially/elimination/findIndex                    2609344.98                +0.58                +1.80                +1.06
serially/elimination/foldl'                         64614.95                +0.11                +0.15                +0.47
serially/elimination/foldl1'                     15371628.28               -10.48                -9.59                -9.08
serially/elimination/foldr                        4577343.57                -0.65                +0.62                +3.06
serially/elimination/foldr1                      13528830.43                -1.84                +3.09                -0.40
serially/elimination/foldrM                       4513326.71                +2.01                +2.17                +1.44
serially/elimination/init                         3034834.37                -0.72                +0.58                +5.98
serially/elimination/last                           64858.78                -0.40                +1.12                +0.50
serially/elimination/length                         65344.12                -0.57                -2.67                +0.01
serially/elimination/mapM_                          65760.89                -1.64                -0.90                +0.79
serially/elimination/maximum                        64598.46                +0.23                +1.87                +1.09
serially/elimination/minimum                        65225.40                +0.07                +0.43                -0.19
serially/elimination/notElem                        48549.79                +0.18                +0.33                +3.33
serially/elimination/nullHeadTail                 2256288.87                +1.49                +3.32                +7.52
serially/elimination/or                             49103.73                +0.57                +3.43                +2.06
serially/elimination/product                        96728.38                +0.50                +0.89                +0.94
serially/elimination/sum                            64969.25                -0.09                +0.89                +1.84
serially/elimination/tail                          791192.50                -0.48                -0.70                +3.77
serially/elimination/toList                       4656027.80                -1.25                +0.26                -1.34
serially/elimination/toNull                         65019.36                -0.07                -1.23                +1.30
```

Here are the same results using bootstrap analysis with ols regression with 1000 resamples. This too reports more run-to-run variance compared to the plain average:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base) default(3)(%)(-base)
--------------------------------------- -------------------- -------------------- -------------------- --------------------
serially/compose/all-in-filters                     97205.47                -0.69                +1.35                +0.24
serially/compose/all-out-filters                    65905.84                -3.37                -3.60                +0.42
serially/compose/map-with-all-in-filter             98083.42                -0.41                -2.63                -1.45
serially/compose/mapM                               63787.32                +3.06                +0.32                +3.58
serially/elimination/all                            47981.46                +1.66                +0.21                +2.68
serially/elimination/and                            48171.17                -0.74                +1.94                -0.29
serially/elimination/any                            48082.00                +1.28                -0.25                +3.76
serially/elimination/elem                           48874.02                -1.35                +0.57                +2.12
serially/elimination/elemIndex                    2618930.37                -1.05                +2.45                -1.22
serially/elimination/find                          623734.94                -1.50                +1.80                +0.50
serially/elimination/findIndex                    2568115.28                +0.60                +7.34                +2.35
serially/elimination/foldl'                         64099.12                +1.82                +9.32                +1.12
serially/elimination/foldl1'                     15456769.28               -11.40                -8.24               -11.85
serially/elimination/foldr                        4562809.39                +2.73                -1.16                +1.89
serially/elimination/foldr1                      13230208.50                +0.44                -2.31                +1.70
serially/elimination/foldrM                       4484875.57                +3.73                +2.14                +0.36
serially/elimination/init                         2997062.30                +1.20                +0.12                +7.90
serially/elimination/last                           63966.35                +0.64                +0.29                +5.40
serially/elimination/length                         63638.12                +1.05                +0.11                +2.94
serially/elimination/mapM_                          63122.99                +2.27                +0.59                +1.94
serially/elimination/maximum                        64056.90                -0.11                -3.36                +1.60
serially/elimination/minimum                        64216.41                +0.44                +0.95                +2.30
serially/elimination/notElem                        48099.10                -0.81                +1.25                +1.25
serially/elimination/nullHeadTail                 2230560.45                +1.43                +0.50                +7.57
serially/elimination/or                             48905.22                -0.40                -3.09                +1.79
serially/elimination/product                        96324.89                -1.92                -0.79                +4.50
serially/elimination/sum                            63932.70                +1.97                +2.58                +5.14
serially/elimination/tail                          791514.25                -0.95                +1.50                +2.15
serially/elimination/toList                       4525962.52                +1.26                +3.09                +0.55
serially/elimination/toNull                         65110.45                -0.81                -0.75                +1.48
```

I think fitting the data to a model may not be much helpful here because the model is quite trivial. If we just compute a plain standard deviation (without any resampling) and remove the outliers, that may be enough to stabilize the results. Or just use the plain standard deviation into account when comparing two runs.

**Comment by harendra-kumar** [comment]
I did another experiment by using a quick mode so that the results have more variance and it will be a better test for the statistical methods. I compared three successive runs of the same code. Following table shows the top deltas across runs using the time determined via the ols regression method:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/elimination/maximum                        43989.14               +58.29               +65.03
serially/filtering/drop-all                         49289.62               +51.38               +23.35
serially/filtering/filter-all-out                   28721.86               +38.67                +4.23
serially/compose/all-in-filters                     61011.03               +38.18               +33.47
serially/filtering/filter-all-in                    42746.19               +37.00                +7.89
serially/transformation/fmap                        63270.91               +30.04               +26.36
serially/generation/unfoldr                         53620.35               +28.00               +30.17
serially/generation/fromList                       447841.12               +25.26               +39.70
serially/filtering/dropWhile-true                   57444.07               +23.04                -8.49
serially/compose/mapM                               57589.57               +22.74               -20.55
```

It show a huge variance (58% and 65% at the top). For the same data, the following table shows the top deltas using mean determined via bootstrap resampling:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/elimination/all                            47198.80                +4.21                +2.50
serially/transformation/concat                        221.39                +3.83                +5.93
serially/elimination/foldl'                         63171.88                +3.39                +4.61
serially/transformation/map                         63331.96                +3.35                +1.07
serially/filtering/filter-all-in                    48723.60                +2.54                -2.05
serially/elimination/nullHeadTail                 2280699.05                +2.33                +1.11
serially/compose/mapM                               65029.11                +2.31                +6.49
serially/transformation/mapMaybe                    98935.42                +2.25                +0.31
serially/elimination/any                            47781.70                +2.04                +0.90
serially/transformation/sequence                  3184372.30                +1.90                +4.21
```

Here we have very small differences (4% and 6% at the top) across runs when we compare the mean. So the mean is much more robust for comparisons. That is what I said earlier based on my general observation, this data confirms that. And here are the top differences using the plain averaging which is even better than the bootstrap method!

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/transformation/concat                        221.34                +3.90                +5.69
serially/elimination/foldl'                         63215.21                +3.30                +4.33
serially/filtering/filter-all-in                    48529.66                +3.26                -1.72
serially/elimination/all                            47306.68                +2.96                +2.54
serially/compose/mapM                               64733.19                +2.89                +6.20
serially/transformation/map                         63524.66                +2.87                +0.91
serially/transformation/mapMaybe                    98499.26                +2.44                +0.78
serially/elimination/nullHeadTail                 2277221.94                +2.27                +0.68
serially/transformation/sequence                  3175180.76                +2.08                +4.57
serially/elimination/foldrM                       4494505.88                +1.54                +0.26
```

**Comment by harendra-kumar** [comment]
I did several such experiments and I am now convinced that we should not report the time determined by ols regression at all. We should only report mean and standard deviation and we should calculate these using the straightforward method and not using the bootstrap resampling method.

@vincenthz if we do this all the statistics code will go away in one fell swoop. Build times will improve and we will have more robust comparisons across benchmark runs. win-win! Unless someone proves me wrong and shows data that this is helpful in some way. The only thing that might be useful are the kde plots but we anyway do not use that in gauge and it can be done via a separate package like bench-graph.

BTW, I used cl95 i.e. 95% confidence level for bootstrap in the experiments above.

**Comment by harendra-kumar** [comment]
What criterion and gauge report as "time" is actually the coefficient of linear regression. The actual time for `i` iterations should be `c + coeff * i` where c is a constant. In the linear regression experiments I reported above what we compared is the coefficient. So the inference from the results is that the coefficient varies wildly whereas the mean does not vary as much.  

If we took `n` samples and the total iterations added up to `j` for all `n` samples then as per the linear equation the mean should be `(c * n / j) + coeff`. If we trust the model to be correct, one hypothesis is that if we increase the number of iterations `j`, the cost per iteration (i.e. the coefficient) increases due to the processing characteristics, but it is compensated by the reduced effect of the constant on the mean because `j` is higher (therefore `c * n / j` would be lower). I can verify this by making sure that `n` and `j` are exactly the same in the experiments being compared.

**Comment by harendra-kumar** [comment]
On a quick look, the total number of samples and iterations is indeed different in the experiments being compared. So we need to somehow make sure that when we are comparing results we keep the samples and iterations exactly the same. How do we do that? Currently we decide the number of iterations dynamically based on minDuration setting. One way to repeat the same experiment is by reading the previous results and repeat those. It will be nice if we can avoid that but it does not look simple if we have to honor the minimum time duration as well.

**Comment by harendra-kumar** [comment]
The default is to take 10 samples at max, it takes 50 or more samples for linear regression coefficient to come closer to the stability of mean, though still not quite as good, the value in parenthesis is the r-square:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/generation/fromList                 626504.37(0.99)                +9.54                +1.10
serially/elimination/findIndex              2390579.82(1.00)                +5.79                +3.94
serially/transformation/map                   61777.32(1.00)                +5.75                +0.69
serially/generation/fromFoldable            1285756.69(0.99)                +5.20                +2.35
serially/elimination/maximum                  60877.24(1.00)                +5.13                +5.96
serially/transformation/elemIndices         5759539.70(0.99)                +5.02                +1.85
serially/elimination/toList                 4168781.21(0.99)                +4.63                +2.27
serially/filtering/take-all                   62348.88(0.99)                +4.43                +1.41
serially/zip                                1307544.49(0.99)                +4.25                +8.95
serially/elimination/elemIndex              2408584.93(1.00)                +3.50                +0.45
```

**Comment by certifiedwaif** [comment]
Aggregating throws away information, and means are trying to find the location/centre of a distribution on the assumption that there is no skew. Means are unstable to outliers, but don't tell you anything _about_ those outliers. So there are situations where one number is not enough, and the mean isn't the number you want. Medians are much more robust to extreme observations, but when benchmarking, the extreme observations may well be the ones you're most interested in.

**Comment by harendra-kumar** [comment]
Makes sense, I can try median as well. In this particular case I am trying to find a stable way to compare two benchmark runs - I need to determine the best possible way to do the experiment (e.g. longer runs are more stable) and an aggregate value that can tell me that two experiments are equivalent with maximum certainty. I know there is going to be some variation across runs and I am not really interested in that in this case. For example, in some of aberrations I see that there are more context switches happening. Since I have a measure of the number of context switches I can try using that as another variable in linear regression and see if that removes the aberration.

**Comment by harendra-kumar** [comment]
Median seems to work the best till now for my purpose, better than the mean. Thanks for pointing it out @certifiedwaif.

```
Benchmark                                default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- --------------------- -------------------- --------------------
serially/generation/unfoldr                 62165.94                +6.04                +1.33
serially/generation/fromList               624881.82                +3.78                +2.05
serially/transformation/concat                226.42                +2.84                +0.87
serially/elimination/findIndex            2454847.79                +2.37                +3.95
serially/elimination/maximum                62145.52                +2.24                +0.17
serially/filtering/dropWhileM-true          76513.33                +2.21                -0.04
serially/elimination/uncons                824067.08                +2.11                +0.62
serially/zipM                             1344283.12                +1.88                +0.02
serially/elimination/elemIndex            2453805.06                +1.78                +2.79
serially/compose/all-out-filters            61354.20                +1.67                +0.14
```

I tried linear regression taking context switches into account but that did not yield noticeably better results. With median the results are quite satisfactory. Next I am going to try if CPU frequency scaling is affecting the results.

**Comment by harendra-kumar** [comment]
Ok, I employed all the three techniques i.e. mean, median and linear regression. I implemented a min diff option in `bench-graph` to show the minimum diff across all and also show the name of the technique which has the minimum variation for that particular experiment. With this here are the top diffs across multiple runs, compare with the previous update which uses only median:

```
Benchmark                               default(0)(ns)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/generation/fromList                 624881.82(0.99)          +2.29(regr)          +1.10(medi)
serially/transformation/concat                  226.42(1.00)          +1.73(regr)          +0.87(medi)
serially/compose/all-out-filters              61354.20(0.99)          +1.59(mean)          +0.14(regr)
serially/zip                                1335949.41(0.99)          +1.59(medi)          -1.05(regr)
serially/generation/fromFoldable            1291999.00(0.99)          +1.41(medi)          -0.83(medi)
serially/elimination/foldr                  4588738.52(0.99)          +1.17(mean)          -2.56(medi)
serially/generation/unfoldr                   62165.94(1.00)          +1.14(medi)          +1.33(medi)
serially/elimination/product                  94897.08(1.00)          +1.13(medi)          +0.13(mean)
serially/elimination/uncons                  824067.08(0.99)          +0.94(medi)          +0.62(medi)
serially/compose/all-in-filters               93147.98(0.99)          +0.90(mean)          +0.85(medi)
```

We now have pretty low variances across runs. We can see that mean and regression coefficient have lower variances in some cases than median. We can use this to definitively establish that there is a performance regression. If the minimum diff across all techniques is more than a min threshold, say +10% then we can say for sure that the benchmark has regressed.

**Comment by harendra-kumar** [comment]
Alright, it seems a laptop causes much more run-to-run variations compared to a desktop, perhaps due to more aggressive power saving/frequency scaling stuff on a laptop. Here are the results on a quadcore desktop computer:

```
Benchmark                               default(0)(μs)(base) default(1)(%)(-base) default(2)(%)(-base)
--------------------------------------- -------------------- -------------------- --------------------
serially/elimination/sum                         89.57(0.01)    +2.03(0.84)(medi)    -0.10(1.00)(regr)
serially/elimination/foldr1                   30682.37(0.09)    +0.57(0.09)(medi)    +0.61(0.09)(medi)
serially/elimination/toList                    9741.94(0.07)    +0.20(0.01)(mean)    +0.42(0.01)(mean)
serially/transformation/scan                     94.35(0.07)    +0.16(0.03)(mean)    -0.05(1.00)(regr)
serially/generation/fromList                   1566.14(0.03)    +0.04(0.03)(medi)    -0.05(0.00)(mean)
serially/elimination/foldl1'                  31312.44(0.09)    +0.02(0.00)(mean)    +0.02(0.09)(medi)
serially/elimination/toNull                      83.97(0.89)    +0.02(0.01)(medi)    +0.01(0.01)(medi)
serially/elimination/findIndex                 4782.85(0.05)    +0.02(1.00)(regr)    +0.06(0.00)(mean)
serially/generation/fromFoldableM              4952.83(0.05)    +0.02(0.05)(medi)    -0.01(0.48)(medi)
```

I have concluded the experiments. The lessons are:

* We need more samples for linear regression to be effective
* Reporting mean is better in more situations (less number of samples, quick mode)
* Median is more robust than mean when we have enough samples and there are significant outliers
*  In case of streamly, and measuring on a laptop, I have found 1 second to be good enough time to give stable results, the default of criterion/gauge is 5 seconds. When measuring on a desktop the time could be even lower.
