### ISSUE TITLE
Multiple iterations with --min-duration=0

### ISSUE THREAD

**Issue by sjakobi** [vincenthz/hs-gauge#94]
I want to run my benchmarks as quickly as possible, just to check that they work.

So I'm using `--time-limit=0` to get only [a single sample](http://hackage.haskell.org/package/gauge-0.2.4/docs/Gauge-Main-Options.html#v:timeLimit) and `--min-duration=0` to get only a single iteration per sample.

Nonetheless `gauge` reports multiple iterations:

```
benchmarking Issue #108/Text ... took 341.6 ms, total 56 iterations
benchmarked Issue #108/Text
time                 6.434 ms   (5.934 ms .. 6.876 ms)
                     0.994 R²   (0.990 R² .. 1.000 R²)
mean                 6.017 ms   (5.917 ms .. 6.214 ms)
std dev              232.3 μs   (131.1 μs .. 337.9 μs)
```

**Comment by harendra-kumar** [comment]
I think`min-samples` overrides `time-limit`.  min-samples is set to 10 in normal mode and 1 in quick mode. So if you use `--quick` then you are good.

Also make sure that you are using `--include-first-iter` if you want absolutely one iteration and no more. If you do not use that option the first iteration results are discarded and one more iteration will be performed.

If this works, you may want to send a PR making the documentation clearer so that others do not stumble on it.

**Comment by sjakobi** [comment]
Thanks for the explanations @harendra-kumar!

I ended up with `--quick --min-duration=0 --include-first-iter` now.

> you may want to send a PR making the documentation clearer

How about I simply remove the way `time-limit` is supposed to affect the number of samples?

**Comment by harendra-kumar** [comment]
> How about I simply remove the way time-limit is supposed to affect the number of samples?

`min-samples` enforces a minimum and `time-limit` enforces a maximum for the same thing. The question is what do we choose when the max turns out to be lower than the min? The options are:

* take the min, which we are doing currently
* take the max, it will have problems dual to the previous one
* Throw an error if we detect that time-limit has reached before min-samples. 

Maybe we can do the third one, so that the user knows what's going on.

**Comment by noughtmare** [comment]
If I use this configuration:

```haskell
defaultConfig
  { includeFirstIter = True
  , minSamples = Just 1
  , timeLimit = Just 0
  , minDuration = 0
  }
```

I get a bunch of errors:

```
memobench-exe: memobench-exe: memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: fewer rows than columns (1,2)
CallStack (from HasCallStack):
  error, called at statistics/Statistics/Regression.hs:71:17 in gauge-0.2.5-AkiLEQr6hv5qvTjI5En3b:Statistics.Regression
memobench-exe: thread blocked indefinitely in an MVar operation
```

Of course running the regression on a single sample is a bit strange, but maybe it could give a better error.
